seed: 1234

batch_size: 75
lr: 1.e-4
total_steps: 800000
warmup_steps: 1
save_interval: 5000
test_interval: 1000
viz_interval: 5000
log_interval: 100
log_eval_interval: 10
data_path: "viper_rl_data/datasets/dmc"
start_iter: 0

ema: 0.9999
optimizer: "adam"
lr_schedule: "constant"

image_size: 64
seq_len: 16
frame_skip: 1
ae_ckpt: "viper_rl_data/checkpoints/dmc_vqgan"
ddp: False
dp: True

ae:
  image_size: 64
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 1
  attn_resolutions: []
  z_channels: 64
  double_z: false
  dropout: 0.
  n_embed: 256
  embed_dim: 64
  patch_size: [8, 8]

n_classes: 17
class_cond: true

model: "videogpt"
transformer:
  embed_dim: 256
  n_head: 8
  n_layer: 8
  mlp_dim: 1024
  dropout: 0.1
  attention_dropout: 0.1
  attn_type: 'full' # 'sparse'

open_loop_ctx: 1
